const RESTAURANT_TABLE_STATUS = {
  AVAILABLE: 'available',
  OCCUPIED: 'occupied',
  RESERVED: 'reserved',
  DISABLED: 'disabled',
}

const SOCKET_EVENT = {
  JOIN_MANAGER: 'join_manager',
  JOIN_ORDER: 'join_order',
  NEW_NOTIFICATION: 'NEW_NOTIFICATION',
  DISH_STATUS_UPDATED: 'DISH_STATUS_UPDATED',
  ORDER_STATUS_UPDATED: 'ORDER_STATUS_UPDATED',
  ORDER_PAID: 'ORDER_PAID',
}

const NOTIFICATION_TYPE_STATUS = {
  NEW_ORDER: 'new_order',
  ORDER_NEW_DISH: 'order_new_dish',
  PAYMENT_REQUEST: 'payment_request',
  STAFF_CALL: 'staff_call',
}

export { RESTAURANT_TABLE_STATUS, SOCKET_EVENT, NOTIFICATION_TYPE_STATUS }
